services:
    app.game.create_command:
        class: AppBundle\Command\Game\CreateCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }

    app.game.list_command:
        class: AppBundle\Command\Game\ListCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
    
    app.game.show_command:
        class: AppBundle\Command\Game\ShowCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
    
    app.game.show.player_command:
        class: AppBundle\Command\Game\ShowPlayerCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
    
    app.game.start_command:
        class: AppBundle\Command\Game\StartCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
    
    app.game_turn.finish_command:
        class: AppBundle\Command\GameTurn\FinishCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }

    app.game_round.finish_command:
        class: AppBundle\Command\GameRound\FinishCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }

    app.game_action_space.drift_mining_command:
        class: AppBundle\Command\GameActionSpace\DriftMiningCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
            
    app.game_action_space.logging_command:
        class: AppBundle\Command\GameActionSpace\LoggingCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }

    app.game_action_space.imitation:
        class: AppBundle\Command\GameActionSpace\ImitationCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
            
    app.game_action_space.excavation:
        class: AppBundle\Command\GameActionSpace\ExcavationCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }

    app.game_action_space.growth:
        class: AppBundle\Command\GameActionSpace\GrowthCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
            
    app.game_action_space.clearing:
        class: AppBundle\Command\GameActionSpace\ClearingCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
            
    app.game_action_space.starting_player_command:
        class: AppBundle\Command\GameActionSpace\StartingPlayerCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }

    app.game_action_space.ore_mining_command:
        class: AppBundle\Command\GameActionSpace\OreMiningCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }

    app.game_action_space.forest_exploration_command:
        class: AppBundle\Command\GameActionSpace\ForestExplorationCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
            
    app.game_action_space.sustenance_command:
        class: AppBundle\Command\GameActionSpace\SustenanceCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }

    app.game_action_space.ruby_mining_command:
        class: AppBundle\Command\GameActionSpace\RubyMiningCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }

    app.game_action_space.housework_command:
        class: AppBundle\Command\GameActionSpace\HouseworkCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }

    app.game_action_space.slash_and_burn_command:
        class: AppBundle\Command\GameActionSpace\SlashAndBurnCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
            
    app.game_action_space.place_meadow_field_twin_tile_command:
        class: AppBundle\Command\GameActionSpace\PlaceMeadowFieldTwinTileCommand
        arguments: ['@caverna.game_engine']
        tags:
            - { name: console.command }
